# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Layout/LineLength:
  Max: 80
  AllowedPatterns:
    - !ruby/regexp /\A *# /

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: symmetrical
